//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_TEST.DB_RAHUL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Emp_Table
    {
        public int Emp_Id { get; set; }
        [Required]
        public string Emp_Name { get; set; }
        [Required]
        public string Emp_Dept_Name { get; set; }
        [Required]
        public string Emp_Comp_Name { get; set; }
        [Required]
        public string Emp_Sal { get; set; }
        [Required]
        public string Emp_Mob { get; set; }
    }
}
